apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

nameSuffix: -dev

replicas:
- name: weather
  count: 1

images:
 - name: quay.io/christian_kirchknopf/weather-app
   newName: quay.io/christian_kirchknopf/weather-app
   newTag: v2.0

patches: 
- patch: |-
    - op: replace
      path: /spec/to/name
      value: weather-dev
  target:
    kind: Route